name: login_app
description: "A new Flutter project for building a login screen."
# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK environment
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

  # Add Google Fonts package for font handling
  google_fonts: ^3.0.0

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section for adding logo or other images
  assets:
    - assets/logo.png

  # Fonts section for adding custom fonts (optional)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf

  # Optionally, if you're using the Google Fonts package:
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - google: roboto

